FROM golang:1.26-alpine
RUN apk add --no-cache git ca-certificates tzdata
RUN go install github.com/air-verse/air@latest
ENV TZ=Asia/Jakarta
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
